;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri Apr 9 2021
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

ORG 0H

    MOV A,#38H ; Use 2 lines and 5x7 matrix
    ACALL COMM
    MOV A,#0CH ; LCD ON, cursor ON
    ACALL COMM
    MOV A,#01H ; Clear screen
    ACALL COMM
    MOV A,#82H ; Cursor line one , position 2
    ACALL COMM
    
    MOV DPTR, #STRING
BACK:   MOV A, #00H
    MOVC A, @A+DPTR
    JZ HERE
    ACALL DISP
    INC DPTR
    SJMP BACK
HERE: SJMP HERE

COMM:   ACALL LCD_DLY
    MOV P3, A
    CLR P1.5 ; RS
    CLR P1.6 ; RW
    SETB P1.7 ; EN
    CLR P1.7 ; EN
    RET

DISP:   ACALL LCD_DLY
    MOV P3, A
    SETB P1.5 ; RS
    CLR P1.6 ; RW
    SETB P1.7 ; EN
    CLR P1.7 ; EN
    RET

LCD_DLY:MOV R0, #0FFH
L1:     MOV R1, #0FFH
    DJNZ R1, $
    DJNZ R0, L1
    RET
    
STRING: DB 'TEST', 0
END